Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -18,6 +18,29 @@ jobs:
     runs-on: ${{ matrix.platform }}
 
     steps:
+      - name: Check for Secret availability
+        id: secret-check
+        # perform secret check & put boolean result as an output
+        shell: bash
+        run: |
+          if [ "${{ secrets.TAURI_PRIVATE_KEY }}" != '' ]; then
+            echo "available=true" >> $GITHUB_OUTPUT;
+          else
+            echo "available=false" >> $GITHUB_OUTPUT;
+          fi
+      - name: Check Inadequate Permissions
+        if: ${{ steps.secret-check.outputs.available != 'true' }}
+        # provide feedback for likely problem, note dependabot cannot access
+        # secrets by default. Secondly, this step forces job failure due to
+        # missing secret via `exit 1`
+        shell: bash
+        run: |
+          if [ "${{ github.actor }}" == "dependabot[bot]" ]; then
+            echo >&2 "Unable to access secrets as unprivileged dependabot.";
+          else
+            echo >&2 "Inadequate Permissions or missing secret value";
+          fi
+          exit 1
       - name: Checkout repository
         uses: actions/checkout@v3
 
@@ -44,21 +67,7 @@ jobs:
       - name: Install frontend dependencies
         # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
         run: npm install # Change this to npm, yarn or pnpm.
-      - name: Check for Secret availability
-        id: secret-check
-        # perform secret check & put boolean result as an output
-        shell: bash
-        run: |
-          if [ "${{ secrets.TAURI_PRIVATE_KEY }}" != '' ]; then
-            echo "available=true" >> $GITHUB_OUTPUT;
-          else
-            echo "available=false" >> $GITHUB_OUTPUT;
-          fi
-          if [ "${{ secrets.TAURI_KEY_PASSWORD }}" != '' ]; then
-            echo "available=true" >> $GITHUB_OUTPUT;
-          else
-            echo "available=false" >> $GITHUB_OUTPUT;
-          fi
+
       - name: Build the app
         uses: tauri-apps/tauri-action@v0
 
